package com.onder.f1PaddockMini.pages

import com.onder.f1PaddockMini.R
import com.onder.f1PaddockMini.core.common.Constants

val BASE_IMAGE_URL = "${Constants.BASE_URL}images/"

val driverImageMap: Map<String, String> = mapOf(
    "max_verstappen" to "${BASE_IMAGE_URL}max.png",
    "norris" to "${BASE_IMAGE_URL}lando.png",
    "leclerc" to "${BASE_IMAGE_URL}leclerc.png",
    "sainz" to "${BASE_IMAGE_URL}sainz.png",
    "piastri" to "${BASE_IMAGE_URL}piastri.png",
    "russell" to "${BASE_IMAGE_URL}russel.png",
    "alonso" to "${BASE_IMAGE_URL}alonso.png",
    "hamilton" to "${BASE_IMAGE_URL}lewis.png",
    "gasly" to "${BASE_IMAGE_URL}gasly.png",
    "antonelli" to "${BASE_IMAGE_URL}antonelli.png",
    "ocon" to "${BASE_IMAGE_URL}ocon.png",
    "albon" to "${BASE_IMAGE_URL}albon.png",
    "tsunoda" to "${BASE_IMAGE_URL}tsunoda.png",
    "hulkenberg" to "${BASE_IMAGE_URL}hulkenberg.png",
    "hadjar" to "${BASE_IMAGE_URL}hadjar.png",
    "bearman" to "${BASE_IMAGE_URL}bearman.png",
    "lawson" to "${BASE_IMAGE_URL}lawson.png",
    "stroll" to "${BASE_IMAGE_URL}stroll.png",
    "bortoleto" to "${BASE_IMAGE_URL}bortoleto.png",
    "colapinto" to "${BASE_IMAGE_URL}colapinto.png",
    "vettel" to "${BASE_IMAGE_URL}vettel.png",
    "bottas" to "${BASE_IMAGE_URL}bottas.png",
    "ricciardo" to "${BASE_IMAGE_URL}ricciardo.png",
    "kevin_magnussen" to "${BASE_IMAGE_URL}magnussen.png",
    "perez" to "${BASE_IMAGE_URL}perez.png",
    "raikkonen" to "${BASE_IMAGE_URL}kimi.png",
    "kubica" to "${BASE_IMAGE_URL}kubica.png",
    "giovinazzi" to "${BASE_IMAGE_URL}giovinazzi.png",
    "mazepin" to "${BASE_IMAGE_URL}mazepin.png",
    "rosberg" to "${BASE_IMAGE_URL}rosberg.png",

    "McLaren" to "${BASE_IMAGE_URL}mclaren.png",
    "Mercedes" to "${BASE_IMAGE_URL}mercedes.png",
    "Red Bull" to "${BASE_IMAGE_URL}redbull.png",
    "Ferrari" to "${BASE_IMAGE_URL}ferrari.png",
    "Williams" to "${BASE_IMAGE_URL}williams.png",
    "RB F1 Team" to "${BASE_IMAGE_URL}rb.png",
    "Aston Martin" to "${BASE_IMAGE_URL}aston_martin.png",
    "Haas F1 Team" to "${BASE_IMAGE_URL}haas.png",
    "Sauber" to "${BASE_IMAGE_URL}sauber.png",
    "Alpine F1 Team" to "${BASE_IMAGE_URL}alpine.png",

    "Australia" to "${BASE_IMAGE_URL}australia.png",
    "China" to "${BASE_IMAGE_URL}china.png",
    "Japan" to "${BASE_IMAGE_URL}japan.png",
    "USA" to "${BASE_IMAGE_URL}usa.png",
    "Canada" to "${BASE_IMAGE_URL}canada.png",
    "Monaco" to "${BASE_IMAGE_URL}monaco.png",
    "Spain" to "${BASE_IMAGE_URL}spain.png",
    "Austria" to "${BASE_IMAGE_URL}austria.png",
    "UK" to "${BASE_IMAGE_URL}uk.png",
    "Belgium" to "${BASE_IMAGE_URL}belgium.png",
    "Hungary" to "${BASE_IMAGE_URL}hungary.png",
    "Netherlands" to "${BASE_IMAGE_URL}netherlands.png",
    "Italy" to "${BASE_IMAGE_URL}italy.png",
    "Azerbaijan" to "${BASE_IMAGE_URL}azerbaijan.png",
    "Singapore" to "${BASE_IMAGE_URL}singapore.png",
    "Mexico" to "${BASE_IMAGE_URL}mexico.png",
    "Brazil" to "${BASE_IMAGE_URL}brazil.png",
    "Qatar" to "${BASE_IMAGE_URL}qatar.jpg",
    "UAE" to "${BASE_IMAGE_URL}uae.jpg",
    "Bahrain" to "${BASE_IMAGE_URL}bahrein.png",
    "Saudi Arabia" to "${BASE_IMAGE_URL}saudi.png",
    "Russia" to "${BASE_IMAGE_URL}russia.png",
    "Turkey" to "${BASE_IMAGE_URL}turkey.png",
    "Portugal" to "${BASE_IMAGE_URL}portugal.png",
    "Germany" to "${BASE_IMAGE_URL}germany.png",
)